name = "FP-2025"
version = "0.1.0"
defaultTargets = ["FunctionalProgramming"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.22.0"

[[lean_lib]]
name = "FunctionalProgramming"

[[lean_exe]]
name = "lecture04"
root = "Main"